### ISSUE TITLE
IDGenerator

### ISSUE THREAD

**Issue by alangregory** [FI-Mihej/Bensbach#1]
From whats package comes import IDGenerator ?

**Comment by FI-Mihej** [comment]
@alangregory it is from [Cengal](https://github.com/FI-Mihej/Cengal): https://github.com/FI-Mihej/Cengal/blob/master/cengal/IDGenerator.py

**Comment by FI-Mihej** [comment]
@alangregory (I'm sorry: I didn't noticed that this repo has an issues opened and even has stars :) )

**Comment by alangregory** [comment]
Thanks, no problem.
Was using it for https://store.steampowered.com/app/681660/Bless_Online/ , but the game is now shutdown.
